### ISSUE TITLE
Steps for installation locally 

### ISSUE THREAD

**Issue by johnfelipe** [renan-siqueira/python-investment-simulation-tool#10]

**Comment by renan-siqueira** [comment]
### 1. Create a Virtual Environment:

- Inside the project directory, create a virtual environment by running:
```bash
python -m venv venv
```
This command creates a virtual environment named venv. You can choose a different name if you like.

### 2. Activate the Virtual Environment:

- On Windows, activate it using:
```bash
venv\Scripts\activate`
```
 or:
 ```bash
 . venv\Scripts\activate` # Git bash terminal or wsl
 ```
- On MacOS/Linux, use `source venv/bin/activate`
- Once activated, you'll see the virtual environment’s name (`venv`) in your command line prompt.

### 3. Install Dependencies:

Install the required packages with:
```bash
pip install -r requirements.txt
```

### 4. Usage:

- Make sure that the paths in the `src/settings/config.py` file are created (in the future I will implement a function to create all the necessary folders automatically)

- Use `data_processor.py` to get historical data of the desired ticker (or tickers). Change "stocks.json" to include the tickers you want to collect and run the command:
```bash
python data_processor.py
```

- After downloading the historical data, open the `main.py` file, locate the `simulate_investment` function call and change the purchase date and sale date to the desired dates (As it is still in development, these dates are hard coded) and execute the command:
```bash
python main.py
```

---

Note: 

1. The project is still in the development process, so some features have not yet been completed, as well as its translation into English.
2. The README will be made as soon as the current functionality is finalized. Configuration and usage information will be present there.

---


**Thank you for being interested in this project and if you need any help or guidance, just post a new pull request. :D**

**Comment by renan-siqueira** [comment]
I just updated the project with the README file.
It is updated with the latest version of the project.
